version: "3"
services:
  db:
    image: tiendzokcros/mysql
    environment:
       MYSQL_ROOT_PASSWORD: nguyenthanhtung
    volumes:
      - ./data:/var/lib/mysql 
  app:
    image: tiendzokcros/event_server
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: nguyenthanhtung
      DB_DATABASE: event
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: nguyenthanhtung
    ports:
      - '8080:80'
    depends_on:
      - db
